site_name: tictactoe
site_description: RESTful API for Tic Tac Toe game
repo_url: https://github.com/sunnyfloyd/tictactoe
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/sunnyfloyd">sunnyfloyd</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
