# Generated by Django 4.0.1 on 2022-01-26 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('finished', 'Finished')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('next_turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_pending_move', to=settings.AUTH_USER_MODEL)),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('column', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('mark', models.CharField(choices=[('o', 'Nought'), ('x', 'Cross')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
